# yaml-language-server: $schema=./../../schema/service.schema.json
apiVersion: v1
kind: ServiceDefinition
id: blotato
metadata:
  name: Blotato
  description: AI content engine
  icon: https://images.mindstudio-cdn.com/images/a47f3f3a-a1fa-41ca-8de3-e415452b4611_1763065279269.png
configuration:
  - id: apiKey
    type: apiKey
    name: API Key
    description: 'Your Blotato API key. To learn about creating an API key, visit: https://help.blotato.com/api/start'
    placeholder: Key...
