# yaml-language-server: $schema=./../../schema/service.schema.json
apiVersion: v1
kind: ServiceDefinition
id: smartsheet
active: false
metadata:
  name: Smartsheet
  description: Work management and collaboration platform
  icon: https://images.mindstudio-cdn.com/images/a47f3f3a-a1fa-41ca-8de3-e415452b4611_1763138381553.png
configuration:
  - id: accessToken
    type: bearerToken
    managed: true
    name: Access Token
    description: Smartsheet API access token
